# Copyright (c) 2022 Gitpod GmbH. All rights reserved.
# Licensed under the GNU Affero General Public License (AGPL).
# See License-AGPL.txt in the project root for license information.

# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/gitpod-io/gitpod/run-gp/cmd.version={{.Version}} -X github.com/gitpod-io/gitpod/run-gp/cmd.commit={{.Commit}} -X github.com/gitpod-io/gitpod/run-gp/cmd.date={{.Date}} -X github.com/gitpod-io/gitpod/run-gp/cmd.builtBy=goreleaser -X github.com/gitpod-io/gitpod/run-gp/pkg/telemetry.segmentKey={{ .Env.SEGMENT_KEY }}
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      amd64: amd64
    format: binary
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
